package ru.gb.zverobukvy.domain.repository.main_menu.shared_preferences

interface SharedPreferencesForGameRepository : TypesCardsSelectedForGameRepository,
    NamesPlayersSelectedForGameRepository, LaunchRepository