package ru.dev4rev.kids.zoobukvy.domain.repository.main_menu.shared_preferences

interface SharedPreferencesForGameRepository : TypesCardsSelectedForGameRepository,
    NamesPlayersSelectedForGameRepository, LaunchRepository