package ru.gb.zverobukvy.utility.ui

import ru.gb.zverobukvy.R

enum class AvatarEnum (val imageName: String, val resId: Int){
    AVATAR_CAT("avatar_cat", R.drawable.avatar_cat),
    AVATAR_DOG("avatar_dog", R.drawable.avatar_dog),
    AVATAR_MOUSE ("avatar_mouse", R.drawable.avatar_mouse),
    AVATAR_BEAR ("avatar_bear", R.drawable.avatar_bear),
    AVATAR_BEAVER ("avatar_beaver", R.drawable.avatar_beaver),
    AVATAR_BEE ("avatar_bee", R.drawable.avatar_bee),
    AVATAR_BUFFALO ("avatar_buffalo", R.drawable.avatar_buffalo),
    AVATAR_BUTTERFLY ("avatar_butterfly", R.drawable.avatar_butterfly),
    AVATAR_CHICKEN ("avatar_chicken", R.drawable.avatar_chicken),
    AVATAR_WHALE ("avatar_whale", R.drawable.avatar_whale),
    AVATAR_COW ("avatar_cow", R.drawable.avatar_cow),
    AVATAR_CRAB ("avatar_crab", R.drawable.avatar_crab),
    AVATAR_DEER ("avatar_deer", R.drawable.avatar_deer),
    AVATAR_DUCK ("avatar_duck", R.drawable.avatar_duck),
    AVATAR_DRAKE ("avatar_drake", R.drawable.avatar_drake),
    AVATAR_ELEPHANT ("avatar_elephant", R.drawable.avatar_elephant),
    AVATAR_FISH ("avatar_fish", R.drawable.avatar_fish),
    AVATAR_FLAMINGO ("avatar_flamingo", R.drawable.avatar_flamingo),
    AVATAR_FOX ("avatar_fox", R.drawable.avatar_fox),
    AVATAR_FROG ("avatar_frog", R.drawable.avatar_frog),
    AVATAR_GIRAFFE ("avatar_giraffe", R.drawable.avatar_giraffe),
    AVATAR_CHAMELEON ("avatar_chameleon", R.drawable.avatar_chameleon),
    AVATAR_HIPPO ("avatar_hippo", R.drawable.avatar_hippo),
    AVATAR_HORSE ("avatar_horse", R.drawable.avatar_horse),
    AVATAR_LADYBUG ("avatar_ladybug", R.drawable.avatar_ladybug),
    AVATAR_LEOPARD ("avatar_leopard", R.drawable.avatar_leopard),
    AVATAR_LION ("avatar_lion", R.drawable.avatar_lion),
    AVATAR_MONKEY ("avatar_monkey", R.drawable.avatar_monkey),
    AVATAR_OCTOPUS ("avatar_octopus", R.drawable.avatar_octopus),
    AVATAR_OWL ("avatar_owl", R.drawable.avatar_owl),
    AVATAR_PANDA ("avatar_panda", R.drawable.avatar_panda),
    AVATAR_RHINO ("avatar_rhino", R.drawable.avatar_rhino),
    AVATAR_SHEEP ("avatar_sheep", R.drawable.avatar_sheep),
    AVATAR_SNAKE ("avatar_snake", R.drawable.avatar_snake),
    AVATAR_TIGER ("avatar_tiger", R.drawable.avatar_tiger),
    AVATAR_WHITE_BEAR ("avatar_white_bear", R.drawable.avatar_white_bear),
    AVATAR_TURTLE ("avatar_turtle", R.drawable.avatar_turtle)
}
